# Generated by Django 2.2.2 on 2020-01-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='CreatedAt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
